{ ... }: {
  imports = [
    ./bat.nix
    ./bottom.nix
    ./cava.nix
    ./eza.nix
    ./firefox.nix
    ./fish.nix
    ./foot.nix
    ./gh.nix
    ./git.nix
    ./gpg.nix
    ./helix.nix
    ./htop.nix
    ./imv.nix
    ./java.nix
    ./joshuto.nix
    ./lazygit.nix
    ./micro.nix
    ./mpv.nix
    ./ncmpcpp.nix
    ./neovim.nix
    ./nix-index.nix
    ./obs.nix
    ./password.nix
    ./pistol.nix
    ./qutebrowser.nix
    ./rofi.nix
    ./swaylock.nix
    ./vscode.nix
    ./waybar.nix
    ./wofi.nix
    ./zathura.nix
    ./zellij.nix
  ];
}
